# Generated by Django 4.2.4 on 2023-08-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarrito', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'carrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('idcomprador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario', models.CharField(blank=True, max_length=45, null=True)),
                ('clave', models.CharField(blank=True, max_length=60, null=True)),
                ('preferencias', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'comprador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallecarrito',
            fields=[
                ('iddetalle', models.IntegerField(primary_key=True, serialize=False)),
                ('precioproducto', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detallecarrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.IntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listadeseo',
            fields=[
                ('idlista', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'listadeseo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('idpaypal', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(blank=True, max_length=40, null=True)),
                ('correo', models.CharField(blank=True, max_length=45, null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('detalles', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'paypal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('foto', models.CharField(blank=True, max_length=50, null=True)),
                ('etiquetas', models.CharField(blank=True, max_length=60, null=True)),
                ('fechavencimiento', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjetacredito',
            fields=[
                ('idtarjetacredito', models.IntegerField(primary_key=True, serialize=False)),
                ('numerotarjeta', models.CharField(blank=True, max_length=45, null=True)),
                ('titular', models.CharField(blank=True, max_length=45, null=True)),
                ('fechavencimiento', models.CharField(blank=True, max_length=45, null=True)),
                ('cvv', models.IntegerField(blank=True, null=True)),
                ('tipotarjeta', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tarjetacredito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('idtransferencia', models.IntegerField(primary_key=True, serialize=False)),
                ('bancoorigen', models.CharField(blank=True, max_length=45, null=True)),
                ('bancodestino', models.CharField(blank=True, max_length=45, null=True)),
                ('numerocuenta', models.CharField(blank=True, max_length=45, null=True)),
                ('cuentadestino', models.CharField(blank=True, max_length=45, null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transferencia',
                'managed': False,
            },
        ),
    ]
