# Generated by Django 4.2.4 on 2023-08-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idcompras', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('total', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idorden', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('subtotal', models.IntegerField(blank=True, null=True)),
                ('cantidadproductos', models.IntegerField(blank=True, null=True)),
                ('metodo', models.CharField(blank=True, max_length=45, null=True)),
                ('fechatransaccion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoOrden',
            fields=[
                ('idproducto_orden', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'producto_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('idreview', models.IntegerField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('idtarjetacredito', models.IntegerField(primary_key=True, serialize=False)),
                ('numerotarjeta', models.CharField(blank=True, max_length=45, null=True)),
                ('titular', models.CharField(blank=True, max_length=45, null=True)),
                ('fechavencimiento', models.CharField(blank=True, max_length=45, null=True)),
                ('cvv', models.IntegerField(blank=True, null=True)),
                ('tipotarjeta', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Tarjetacredito',
        ),
    ]
