# Generated by Django 4.2.4 on 2023-09-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onlinestore', '0003_delete_categoria_delete_comprador_delete_compras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('idbank_transfer', models.IntegerField(primary_key=True, serialize=False)),
                ('origin_bank', models.CharField(blank=True, max_length=45, null=True)),
                ('destination_bank', models.CharField(blank=True, max_length=45, null=True)),
                ('acount_number', models.CharField(blank=True, max_length=45, null=True)),
                ('destination_account_number', models.CharField(blank=True, max_length=45, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bank_transfer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('idbuyer', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('usurarname', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=60, null=True)),
                ('preferences', models.JSONField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'buyer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('idcreditcard', models.IntegerField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=45, null=True)),
                ('cvv', models.IntegerField(blank=True, null=True)),
                ('card_type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('iddetails', models.IntegerField(primary_key=True, serialize=False)),
                ('product_units', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idcategory', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('idcompany', models.IntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('message', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('idorder', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('subtotal', models.IntegerField(blank=True, null=True)),
                ('products_amount', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=45, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('idpaypal', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('details', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'paypal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idproduct', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('code', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_quantity', models.IntegerField(blank=True, null=True)),
                ('quantity_sold', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.CharField(blank=True, max_length=90, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('idproducto_order', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'product_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('idpurchases', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('total', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'purchases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('idreview', models.IntegerField(primary_key=True, serialize=False)),
                ('stars', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('idwishlist', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wishlist',
                'managed': False,
            },
        ),
    ]
