# Generated by Django 4.2.4 on 2023-10-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelTable(
            name='company',
            table='order',
        ),
    ]
