# Generated by Django 4.1 on 2023-11-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchases',
        ),
    ]
