# Generated by Django 4.2.4 on 2023-10-16 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0005_alter_order_options_alter_company_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_idbuyer',
            field=models.ForeignKey(db_column='buyer_idbuyer', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='onlinestore.buyer'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='onlinestore.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='purchases_idpurchases',
            field=models.ForeignKey(db_column='purchases_idpurchases', default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='onlinestore.purchases'),
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
